# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{puavo-view-helpers}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jouni Korhonen"]
  s.date = %q{2012-09-04}
  s.description = %q{View helpers for Puavo applications}
  s.email = %q{puavo@opinsys.fi}
  s.extra_rdoc_files = [
    "COPYING",
    "README.md",
    "init.rb"
  ]
  s.files = [
    "COPYING",
    "README.md",
    "init.rb",
    "lib/view_helpers.rb",
    "rails/init.rb"
  ]
  s.homepage = %q{https://github.com/jpkorhonen/puavo-view-helpers}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{View helpers for Puavo applications}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

